name: Calculator CI

on:
  workflow_dispatch:
    inputs:
      initialValue:
        description: 'The initial value'
        required: true
        default: 0
jobs:
  addition:
    name: Addition
    runs-on: ubuntu-20.04
    steps:
      - name: One
        id: one
        run: |
          echo "::set-output name=one::1"

      - name: Two
        id: two
        run: |
          echo "::set-output name=two::2"


      - name: Three
        id: three
        run: |
          echo "::set-output name=three::3"

      - name: Result
        id: result
        run: |
          echo "INITIAL: ${{ github.event.inputs.initialValue }}"
          result=$(( ${{ github.event.inputs.initialValue }} + ${{ steps.one.outputs.one }} + ${{ steps.two.outputs.two }}  +  ${{ steps.three.outputs.three }} ))
          printf "Result: %s\n" $result