on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.2' 

      - name: Tools Versions
        run: |
          make --version
          go version

      - name: Vet
        run: make vet